---
title: "Autoregressive example"
output: html_notebook
---

```{r}
rm(list=ls())
library(tidyverse)
library(reshape2)
library(rstan)
library(latex2exp)
library(caret)
library(gbm)
library(mvtnorm)
options(mc.cores=4)
rstan_options(auto_write = TRUE)
source("monitornew.R")
source("r_star_monitor.R")
```

Functions to generate simulated data
```{r}
f_ar1 <- function(rho, sigma, L){
  x <- vector(length = L)
  x[1] <- rnorm(1, 0, sd=sigma)
  for(i in 2:L)
    x[i] = rho * x[i - 1] + rnorm(1, 0, sd=sigma)
  return(x)
}

# Generates three chains with same var; one with a different var
f_generate_lower_var_four <- function(var_ratio, rho, sigma, L){
  x <- matrix(nrow = L, ncol = 4)
  for(i in 1:3)
    x[, i] <- f_ar1(rho, sigma, L)
  z <- f_ar1(rho, sigma * sqrt(var_ratio), L)
  x[, 4] <- z
  return(x)
}
```

Calculate R* and Rhat across 200 replicates
```{r}
f_replicate <- function(){
  temp <- f_generate_lower_var_four(1/4, 0.3, 1, 2000)
  a_array <- array(dim=c(2000, 4, 1))
  a_array[,,1] <- temp
  a_accuracy <- r_star(a_array, method = "xgbTree")
  mon <- monitor_extra(split_data(a_array))
  return(list(r_star=a_accuracy, r_hat=mon$zfsRhat))
}

nreplicates <- 200
r_star_vals <- vector(length = nreplicates)
r_hat_vals <- vector(length = nreplicates)
for(i in 1:nreplicates){
    print(i)
  
  temp <- f_replicate()
  r_star_vals[i] <- temp$r_star
  r_hat_vals[i] <- temp$r_hat
}

saveRDS(tibble(r_star=r_star_vals, r_hat=r_hat_vals), "../data/ar1_r_star_hat.rds")
```

Plot results
```{r}
reses <- readRDS("../data/ar1_r_star_hat.rds")
r_star_vals <- reses$r_star 
r_hat_vals <- reses$r_hat 
g2 <- tibble(accuracy=r_star_vals, iteration=seq(1, nreplicates, 1)) %>% 
  ggplot(aes(x=accuracy)) +
  geom_histogram() +
  xlab(TeX("$R*$")) +
  ylab("Count") +
  ggtitle("B.") +
  theme(text = element_text(size=18, colour="black"),
        axis.text = element_text(colour="black", size=16)) +
  xlim(0.9, NA)

g2a <- tibble(accuracy=r_hat_vals, iteration=seq(1, nreplicates, 1)) %>% 
  ggplot(aes(x=accuracy)) +
  geom_histogram() +
  xlab(TeX("Split-$\\hat{R}$")) +
  ylab("Count") +
  ggtitle("C.") +
  theme(text = element_text(size=18, colour="black"),
        axis.text = element_text(colour="black", size=16)) +
  xlim(1, NA)
```

Look at predictions of model
```{r}
# add in a column of noise since gbm requires >1 variables
full_data <- f_generate_lower_var_four(1/4, 0.3, 1, 2000) %>% 
  melt() %>% 
  select(-Var1) %>% 
  rename(chain=Var2) %>% 
  mutate(ran_val=rnorm(8000)) %>% 
  mutate(chain=as.factor(chain))
caretGrid <- tibble(nrounds = c(100),
                        max_depth = c(4),
                        eta = c(.4),
                        gamma = 0,
                        colsample_bytree = .7,
                        min_child_weight = 1,
                        subsample = 0.8)

rand_samples <- sample(1:nrow(full_data), 0.7 * nrow(full_data))
training_data <- full_data[rand_samples, ]
testing_data <- full_data[-rand_samples, ]
gbmFit1 <- train(chain ~ ., data = training_data, 
                 method = "xgbTree",
                 trControl = trainControl(method = 'none'), 
                 verbose=FALSE, tuneGrid = caretGrid)

g1 <- testing_data %>% 
  arrange(value) %>% 
  mutate(predictions=predict(object=gbmFit1, .)) %>% 
  ggplot(aes(x=value, y=predictions)) +
  geom_jitter(height = 0.3) +
  xlab("Value") +
  ylab("Chain classification") +
  theme(text = element_text(size=18, colour="black"),
        axis.text = element_text(colour="black")) +
  coord_flip() +
  ggtitle("A.")
```


Generate R* distribution based on 2000 iterations for run where chain has lower variance and another where all four chains have same variance
```{r}
temp <- f_generate_lower_var_four(1/4, 0.3, 1, 2000) 
temp1 <- matrix(rnorm(8000), nrow = 2000)
a_array <- array(dim=c(2000, 4, 2))
a_array[,,1] <- temp
a_array[,,2] <- temp1
unmixed <- r_star(a_array, uncertainty = T, method = "xgbTree")

temp <- f_generate_lower_var_four(1, 0.3, 1, 2000)
temp1 <- matrix(rnorm(8000), nrow = 1000)
a_array <- array(dim=c(2000, 4, 2))
a_array[,,1] <- temp
a_array[,,2] <- temp1
mixed <- r_star(a_array, uncertainty = T, method = "xgbTree")

mAR1 <- tibble(unmixed, mixed)
g3 <- 
  mAR1 %>% 
  melt() %>% 
  ggplot(aes(x=value, fill=as.factor(variable))) +
  geom_histogram(position="identity", alpha=0.8) +
  scale_fill_grey("Series", labels=c("Unmixed", "Mixed")) +
  xlab(TeX("$R*$")) +
  ylab("Count") +
  geom_vline(xintercept = 1, linetype=2) +
  ggtitle("D.") +
  theme(text = element_text(size=18, colour="black"),
        axis.text = element_text(colour="black"),
        legend.position = c(0.8, 0.8))

pdf("../output/ar1.pdf", width = 12, height = 6)
multiplot(g1, g2a, g2, g3, cols = 2)
dev.off()
```

# Performance as a function of number of chains
```{r}
f_generate_lower_var_n <- function(n_chains, var_ratio, rho, sigma, L){
  x <- matrix(nrow = L, ncol = n_chains)
  for(i in 1:(n_chains - 1))
    x[, i] <- f_ar1(rho, sigma, L)
  z <- f_ar1(rho, sigma * sqrt(var_ratio), L)
  x[, n_chains] <- z
  return(x)
}

f_replicate_n <- function(n_chains){
  temp <- f_generate_lower_var_n(n_chains, 1/4, 0.3, 1, 2000)
  a_array <- array(dim=c(2000, n_chains, 1))
  a_array[,,1] <- temp
  a_accuracy <- r_star(a_array, method="xgbTree")
  mon <- monitor_extra(split_data(a_array))
  return(list(r_star=a_accuracy, r_hat=mon$zfsRhat))
}

nreplicates <- 50
lnum_chains <- c(2, 4, 6, 8, 16, 32, 64)
mResults <- matrix(nrow = nreplicates * length(lnum_chains),
                   ncol = 4)
k <- 1
for(j in seq_along(lnum_chains)){
  print(j)
  for(i in 1:nreplicates){
    temp <- f_replicate_n(lnum_chains[j])
    mResults[k, ] <- c(lnum_chains[j], i, temp$r_star, temp$r_hat)
    k <- k + 1
  }
}

colnames(mResults) <- c("nchains", "iterate", "R*", "split-Rhat")
mResults <- as.data.frame(mResults)
saveRDS(mResults, "../data/ar1_numchains.rds")
mResults <- readRDS("../data/ar1_numchains.rds")
b_sum <- mResults %>% 
  melt(id.vars=c("nchains", "iterate")) %>%
  group_by(nchains, variable) %>% 
  summarise(lower=quantile(value, 0.25),
         upper=quantile(value, 0.75),
         middle=quantile(value, 0.5))

g <- mResults %>% 
  melt(id.vars=c("nchains", "iterate")) %>% 
  left_join(b_sum, by = c("nchains", "variable")) %>% 
  mutate(variable=if_else(variable=="split-Rhat", "Split-Rhat", as.character(variable))) %>% 
  ggplot(aes(x=as.factor(nchains), y=value)) +
  geom_jitter(width = 0.2, colour="grey") +
  geom_pointrange(aes(ymin=lower, y=middle, ymax=upper)) +
  facet_wrap(~variable) +
  scale_x_discrete() +
  xlab("# chains") +
  ylab("Value") +
  scale_color_grey() +
  theme(axis.text = element_text(colour="black", size=16),
        axis.title = element_text(colour="black", size=16),
        strip.text.x = element_text(colour="black", size=16),
        legend.position = "none")
ggsave("../output/ar1_numchains.pdf", g, width = 8, height = 4)
```

# Investigating stochasticity of R*
```{r}
f_replicate_samplesize <- function(temp, samplesize){
  a_array <- array(dim=c(samplesize, 4, 1))
  a_array[,,1] <- temp
  a_accuracy <- r_star(a_array)
  return(list(r_star=a_accuracy))
}


lsample_sizes <- c(500, 1000, 2000, 4000, 8000)
nreplicates <- 100
mResults <- matrix(nrow = nreplicates * length(lsample_sizes),
                   ncol = 3)
k <- 1
for(j in seq_along(lsample_sizes)){
  print(j)
  x <- f_generate_lower_var_four(1/4, 0.3, 1, lsample_sizes[j])
  for(i in 1:nreplicates){
    temp <- f_replicate_samplesize(x, lsample_sizes[j])
    mResults[k, ] <- c(lsample_sizes[j], i, temp$r_star)
    k <- k + 1
  }
}

colnames(mResults) <- c("n", "iterate", "R*")
mResults <- as.data.frame(mResults)
saveRDS(mResults, "../data/ar1_numsamples.rds")
mResults <- readRDS("../data/ar1_numsamples.rds")

b_sum <- mResults %>% 
  melt(id.vars=c("n", "iterate")) %>%
  group_by(n, variable) %>% 
  summarise(lower=quantile(value, 0.025),
         upper=quantile(value, 0.975),
         middle=quantile(value, 0.5))

g <- mResults %>% 
  melt(id.vars=c("n", "iterate")) %>% 
  left_join(b_sum, by = c("n", "variable")) %>% 
  filter(variable!="split-Rhat") %>% 
  ggplot(aes(x=as.factor(n), y=value)) +
  geom_jitter(width = 0.2, colour="grey") +
  geom_pointrange(aes(ymin=lower, y=middle, ymax=upper)) +
  scale_x_discrete() +
  xlab("Sample size") +
  ylab(TeX("Split-R*")) +
  scale_color_grey() +
  theme(axis.text = element_text(colour="black", size=16),
        axis.title = element_text(colour="black", size=20),
        strip.text.x = element_text(colour="black", size=16),
        legend.position = "none")
ggsave("../output/ar1_samplesize.pdf", g, width = 8, height = 6)
```
