---
title: "Discrete target distribution examples"
output: html_notebook
---

```{r}
rm(list=ls())
library(tidyverse)
library(reshape2)
library(rstan)
library(latex2exp)
library(caret)
library(gbm)
library(MCMCpack)
options(mc.cores=4)
rstan_options(auto_write = TRUE)
source("monitornew.R")
source("r_star_monitor.R")
```

Create a discrete Markov chain
```{r}
f_simulate_markov_chain <- function(L, P, state_0){
  states <- vector(length=L)
  states[1] <- state_0
  for(i in 2:L){
    p  <- P[states[i - 1], ]
    states[i] <-  which(rmultinom(1, 1, p) == 1)
  }
  return(states)
}

P <- matrix(nrow = 4, ncol = 4)
P[1, ] <- c(0, 1/2, 1/2, 0)
P[2, ] <- c(1/2, 0, 1/3, 1/6)
P[3, ] <- c(1/4, 1/4, 1/4, 1/4)
P[4, ] <- c(0, 1, 0, 0)
 
states <- f_simulate_markov_chain(100, P, 1)
plot(states, type="l")
```

Create 3 Markov chains with same transition matrix; one with a slightly different one
```{r}
f_generate_four <- function(L, P0, P1, state_0){
  x <- matrix(nrow = L, ncol = 4)
  for(i in 1:3)
    x[, i] <- f_simulate_markov_chain(L, P0, state_0)
  x[, 4] <- f_simulate_markov_chain(L, P1, state_0)
  return(x)
}

P0 <- P
P1 <- matrix(nrow = 4, ncol = 4)
P1[1, ] <- c(0, 1/2, 1/2, 0)
P1[2, ] <- c(1/2, 0, 1/3, 1/6)
P1[3, ] <- c(1, 0, 0, 0)
P1[4, ] <- c(1, 0, 0, 0)

f_generate_four(1000, P0, P1, 1) %>% 
  as.data.frame() %>% 
  rename(chain_1=V1, chain_2=V2, chain_3=V3, chain_4=V4) %>% 
  mutate(iter=seq_along(chain_1)) %>% 
  melt(id.vars="iter") %>% 
  group_by(variable) %>% 
  summarise(state_1=mean(value==1),
            state_2=mean(value==2),
            state_3=mean(value==3),
            state_4=mean(value==4)) %>% 
  pivot_longer(cols=state_1:state_4) %>% 
  ggplot(aes(x=as.factor(name), fill=as.factor(variable), y=value)) +
  geom_col(position = position_dodge()) +
  xlab("State") +
  ylab("Frequency") +
  scale_fill_brewer("Chain", palette = "Dark2")
```

Generate replicates and calculate R* on these
```{r}
f_replicate <- function(L, P0, P1, state_0){
  temp <- f_generate_four(L, P0, P1, state_0)
  a_array <- array(dim=c(L, 4, 1))
  a_array[,,1] <- temp
  a_accuracy <- r_star(a_array, method = "gbm")
  mon <- monitor_extra(a_array)
  rhat <- max(mon$zsRhat, mon$zfsRhat)
  return(list(r_star=a_accuracy, r_hat=rhat))
}

nreplicates <- 40
Ls <- c(1000, 2000, 5000, 10000)

# create P1 matrices
f_create_P1_example <- function(per_along){
  P1 <- matrix(nrow = 4, ncol = 4)
  P1[1, ] <- c(0, 1/2, 1/2, 0)
  P1[2, ] <- c(1/2, 0, 1/3, 1/6)
  v_diff <- c(1, 0, 0, 0) - c(1/4, 1/4, 1/4, 1/4)
  P1[3, ] <- c(1/4, 1/4, 1/4, 1/4) + v_diff * per_along
  v_diff <- c(1, 0, 0, 0) - c(0, 1, 0, 0)
  P1[4, ] <- c(0, 1, 0, 0) + v_diff * per_along
  return(P1)
}

last_vals <- c(0, 0.5, 1)
P1s <- map(last_vals, ~f_create_P1_example(.))

r_star_vals <- matrix(nrow=nreplicates * length(Ls) * length(P1s), ncol=4)
r_hat_vals <- matrix(nrow=nreplicates * length(Ls) * length(P1s), ncol=4)
counter <- 1
for(k in 1:length(P1s)){
  for(j in seq_along(Ls)){
    print(paste0("k=", k, ", j=", j))
    for(i in 1:nreplicates){
      temp <- f_replicate(Ls[j], P0, P1s[[k]], 1)
      r_star_vals[counter, ] <- c(k, Ls[j], i, temp$r_star)
      r_hat_vals[counter, ] <- c(k, Ls[j], i, temp$r_hat)
      counter <- counter + 1
    }
  }
}
colnames(r_hat_vals) <- c("P1", "sample size", "iter", "value")
colnames(r_star_vals) <- c("P1", "sample size", "iter", "value")
r_hat_vals <- as.data.frame(r_hat_vals) %>% 
  mutate(type="Split-Rhat")
r_star_vals <- as.data.frame(r_star_vals) %>% 
  mutate(type="R*")

saveRDS(list(r_star=r_star_vals, r_hat=r_hat_vals), "../data/discrete_r_star_hat.rds")
```

Plot
```{r}
temp <- readRDS("../data/discrete_r_star_hat.rds")
r_star_vals <- temp$r_star %>% 
  mutate(P1=if_else(P1==1, "P1", if_else(P1==2, "P2", "P3"))) %>% 
  mutate(`sample size`=as.character(`sample size`)) %>% 
  mutate(`sample size`=if_else(`sample size`=="10000", "10,000", `sample size`)) %>% 
  mutate(`sample size`=as.factor(`sample size`)) %>% 
  mutate(`sample size`=fct_relevel(`sample size`, "1000", "2000", "5000", "10,000"))
a_sum <- r_star_vals %>%
  group_by(P1, `sample size`, type) %>%
  summarise(lower=quantile(value, 0.025),
         upper=quantile(value, 0.975),
         middle=quantile(value, 0.5))
g1 <- r_star_vals %>% 
  left_join(a_sum) %>% 
  ggplot(aes(x=as.factor(`sample size`), y=value)) +
  geom_jitter(width = 0.2, colour="grey") +
  geom_pointrange(aes(ymin=lower, y=middle, ymax=upper)) +
  facet_grid(vars(P1)) +
  geom_hline(yintercept = 1, linetype=2) +
  scale_y_continuous(limits=c(NA, NA)) +
  xlab("Sample size") +
  ylab(TeX("$R*$")) +
  theme(axis.text = element_text(colour="black", size=16),
        axis.title = element_text(colour="black", size=16),
        strip.text.y = element_text(colour="black", size=16),
        legend.position = "none",
        title = element_text(colour="black", size=16)) +
  ggtitle("A.")
r_star_vals <- temp$r_hat %>% 
  mutate(P1=if_else(P1==1, "P1", if_else(P1==2, "P2", "P3"))) %>% 
  mutate(`sample size`=as.character(`sample size`)) %>% 
  mutate(`sample size`=if_else(`sample size`=="10000", "10,000", `sample size`)) %>% 
  mutate(`sample size`=as.factor(`sample size`)) %>% 
  mutate(`sample size`=fct_relevel(`sample size`, "1000", "2000", "5000", "10,000"))
a_sum <- r_star_vals %>%
  group_by(P1, `sample size`, type) %>%
  summarise(lower=quantile(value, 0.025),
         upper=quantile(value, 0.975),
         middle=quantile(value, 0.5))
g2 <- r_star_vals %>% 
  left_join(a_sum) %>% 
  ggplot(aes(x=as.factor(`sample size`), y=value)) +
  geom_jitter(width = 0.2, colour="grey") +
  geom_pointrange(aes(ymin=lower, y=middle, ymax=upper)) +
  facet_grid(vars(P1)) +
  geom_hline(yintercept = 1, linetype=2) +
  scale_y_continuous(limits=c(NA, NA)) +
  xlab("Sample size") +
  ylab(TeX("Split-$\\hat{R}$")) +
  theme(axis.text = element_text(colour="black", size=16),
        axis.title = element_text(colour="black", size=16),
        strip.text.y = element_text(colour="black", size=16),
        legend.position = "none",
        title = element_text(colour="black", size=16)) +
  ggtitle("B.")

multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

pdf("../output/discrete.pdf", width = 12, height = 8)
multiplot(g1, g2, cols = 1)
dev.off()
```

Plotting stationary distributions
```{r}
m_stationary <- matrix(c(11/46, 15/46, 14/46, 6/46, 71/198, 17/66, 10/33, 8/99, 4/9, 2/9, 8/27, 1/27), nrow = 3, byrow = T) %>% 
  as.data.frame() %>% 
  mutate(matrix=c("P1", "P2", "P3"))
colnames(m_stationary)[1:4] <- c("1", "2", "3", "4")
g <- m_stationary %>% 
  melt(id.vars="matrix") %>% 
  ggplot(aes(x=as.factor(variable), y=value, fill=as.factor(matrix))) +
  geom_col(position = position_dodge()) +
  xlab("State") +
  ylab("Probability") +
  scale_fill_brewer("Transition\nprobability\nmatrix", palette = "Dark2", labels=unname(TeX(c("P_1", "P_2", "P_3")))) +
  theme(axis.text = element_text(colour="black", size=16),
        axis.title = element_text(colour="black", size=16),
        strip.text.x = element_text(colour="black", size=16),
        legend.text = element_text(colour="black", size=16),
        legend.title = element_text(colour="black", size=16),
        legend.position = c(0.85, 0.7))
ggsave("../output/discrete_stationary.pdf", g, width = 10, height = 6)
```

# Higher dimension discrete Markov chain
```{r}
f_construct_random_matrix <- function(n_dim, alpha){
  P <- rdirichlet(n_dim, alpha)
  return(P)
}

# P0 <- f_construct_random_matrix(20, rep(1, 20))
# P1 <- f_construct_random_matrix(20, rep(1, 20))

# saveRDS(list(P0=P0, P1=P1), "../data/discrete_higherd_matrices.rds")
temp <- readRDS("../data/discrete_higherd_matrices.rds")
P0 <- temp$P0
P1 <- temp$P1
# show first few stationary frequencies for the chains
g <- f_generate_four(100000, P0, P1, 1) %>% 
  as.data.frame() %>% 
  rename(chain_1=V1, chain_2=V2, chain_3=V3, chain_4=V4) %>% 
  mutate(iter=seq_along(chain_1)) %>% 
  melt(id.vars="iter") %>% 
  group_by(variable) %>% 
  summarise("1"=mean(value==1),
            "2"=mean(value==2),
            "3"=mean(value==3),
            "4"=mean(value==4)) %>% 
  pivot_longer(cols="1":"4") %>% 
  mutate(variable=if_else(variable=="chain_1", "1", if_else(variable=="chain_2", "2", if_else(variable=="chain_3", "3", "4")))) %>% 
  ggplot(aes(x=as.factor(name), fill=as.factor(variable), y=value)) +
  geom_col(position = position_dodge()) +
  xlab("State") +
  ylab("Frequency") +
  scale_fill_brewer("Chain", palette = "Dark2") +
  theme(axis.text = element_text(colour="black", size=16),
        axis.title = element_text(colour="black", size=16),
        strip.text.y = element_text(colour="black", size=16),
        title = element_text(colour="black", size=16),
        legend.text = element_text(colour="black", size=16))
# ggsave("../output/discrete_stationary_higherd.pdf", g, width = 10, height = 6)
```

Do same simulations as before but with this higher dimensional case
```{r}
nreplicates <- 40
Ls <- c(1000, 2000, 5000, 10000)
P1s <- list(P0, P1)

r_star_vals <- matrix(nrow=nreplicates * length(Ls) * length(P1s), ncol=4)
r_hat_vals <- matrix(nrow=nreplicates * length(Ls) * length(P1s), ncol=4)
counter <- 1
for(k in 1:length(P1s)){
  for(j in seq_along(Ls)){
    print(paste0("k=", k, ", j=", j))
    for(i in 1:nreplicates){
      temp <- f_replicate(Ls[j], P0, P1s[[k]], 1)
      r_star_vals[counter, ] <- c(k, Ls[j], i, temp$r_star)
      r_hat_vals[counter, ] <- c(k, Ls[j], i, temp$r_hat)
      counter <- counter + 1
    }
  }
}
colnames(r_hat_vals) <- c("P1", "sample size", "iter", "value")
colnames(r_star_vals) <- c("P1", "sample size", "iter", "value")
r_hat_vals <- as.data.frame(r_hat_vals) %>% 
  mutate(type="Split-Rhat")
r_star_vals <- as.data.frame(r_star_vals) %>% 
  mutate(type="R*")

saveRDS(list(r_star=r_star_vals, r_hat=r_hat_vals), "../data/discrete_r_star_hat_higherd.rds")

temp <- readRDS("../data/discrete_r_star_hat_higherd.rds")
r_star_vals <- temp$r_star %>% 
  mutate(P1=if_else(P1==1, "P1", if_else(P1==2, "P2", "P3"))) %>% 
  mutate(`sample size`=as.character(`sample size`)) %>% 
  mutate(`sample size`=if_else(`sample size`=="10000", "10,000", `sample size`)) %>% 
  mutate(`sample size`=as.factor(`sample size`)) %>% 
  mutate(`sample size`=fct_relevel(`sample size`, "1000", "2000", "5000", "10,000"))
a_sum <- r_star_vals %>%
  group_by(P1, `sample size`, type) %>%
  summarise(lower=quantile(value, 0.025),
         upper=quantile(value, 0.975),
         middle=quantile(value, 0.5))
g1 <- r_star_vals %>% 
  left_join(a_sum) %>% 
  ggplot(aes(x=as.factor(`sample size`), y=value)) +
  geom_jitter(width = 0.2, colour="grey") +
  geom_pointrange(aes(ymin=lower, y=middle, ymax=upper)) +
  facet_grid(vars(P1)) +
  geom_hline(yintercept = 1, linetype=2) +
  scale_y_continuous(limits=c(NA, NA)) +
  xlab("Sample size") +
  ylab(TeX("$R*$")) +
  theme(axis.text = element_text(colour="black", size=16),
        axis.title = element_text(colour="black", size=16),
        strip.text.y = element_text(colour="black", size=16),
        legend.position = "none",
        title = element_text(colour="black", size=16)) +
  ggtitle("A.")
r_star_vals <- temp$r_hat %>% 
  mutate(P1=if_else(P1==1, "P1", if_else(P1==2, "P2", "P3"))) %>% 
  mutate(`sample size`=as.character(`sample size`)) %>% 
  mutate(`sample size`=if_else(`sample size`=="10000", "10,000", `sample size`)) %>% 
  mutate(`sample size`=as.factor(`sample size`)) %>% 
  mutate(`sample size`=fct_relevel(`sample size`, "1000", "2000", "5000", "10,000"))
a_sum <- r_star_vals %>%
  group_by(P1, `sample size`, type) %>%
  summarise(lower=quantile(value, 0.025),
         upper=quantile(value, 0.975),
         middle=quantile(value, 0.5))
g2 <- r_star_vals %>% 
  left_join(a_sum) %>% 
  ggplot(aes(x=as.factor(`sample size`), y=value)) +
  geom_jitter(width = 0.2, colour="grey") +
  geom_pointrange(aes(ymin=lower, y=middle, ymax=upper)) +
  facet_grid(vars(P1)) +
  geom_hline(yintercept = 1, linetype=2) +
  scale_y_continuous(limits=c(NA, NA)) +
  xlab("Sample size") +
  ylab(TeX("Split-$\\hat{R}$")) +
  theme(axis.text = element_text(colour="black", size=16),
        axis.title = element_text(colour="black", size=16),
        strip.text.y = element_text(colour="black", size=16),
        legend.position = "none",
        title = element_text(colour="black", size=16)) +
  ggtitle("B.")

pdf("../output/discrete_higherd.pdf", width = 12, height = 8)
multiplot(g1, g2, cols = 1)
dev.off()
```

