---
title: "Discrete target distribution examples"
output: html_notebook
---

```{r}
rm(list=ls())
library(tidyverse)
library(reshape2)
library(rstan)
library(latex2exp)
library(caret)
library(gbm)
library(MCMCpack)
options(mc.cores=4)
rstan_options(auto_write = TRUE)
source("monitornew.R")
source("r_star_monitor.R")
```

Create a discrete Markov chain
```{r}
f_simulate_markov_chain <- function(L, P, state_0){
  states <- vector(length=L)
  states[1] <- state_0
  for(i in 2:L){
    p  <- P[states[i - 1], ]
    states[i] <-  which(rmultinom(1, 1, p) == 1)
  }
  return(states)
}

P <- matrix(nrow = 4, ncol = 4)
P[1, ] <- c(0, 1/2, 1/2, 0)
P[2, ] <- c(1/2, 0, 1/3, 1/6)
P[3, ] <- c(1/4, 1/4, 1/4, 1/4)
P[4, ] <- c(0, 1, 0, 0)
```

Create 3 Markov chains with same transition matrix; one with a slightly different one
```{r}
f_generate_four <- function(L, P0, P1, state_0){
  x <- matrix(nrow = L, ncol = 4)
  for(i in 1:3)
    x[, i] <- f_simulate_markov_chain(L, P0, state_0)
  x[, 4] <- f_simulate_markov_chain(L, P1, state_0)
  return(x)
}

P0 <- P
P1 <- matrix(nrow = 4, ncol = 4)
P1[1, ] <- c(0, 1/2, 1/2, 0)
P1[2, ] <- c(1/2, 0, 1/3, 1/6)
P1[3, ] <- c(1, 0, 0, 0)
P1[4, ] <- c(1, 0, 0, 0)
```

Generate replicates for both zfs-Rhat and s-Rhat
```{r}
f_replicate <- function(L, P0, P1, state_0){
  temp <- f_generate_four(L, P0, P1, state_0)
  a_array <- array(dim=c(L, 4, 1))
  a_array[,,1] <- temp
  mon <- monitor_extra(split_data(a_array))
  return(list(r_hat_zfs=mon$zfsRhat, r_hat_s=mon$sRhat))
}

nreplicates <- 5
Ls <- c(1000, 2000, 5000, 10000)

# create P1 matrices
f_create_P1_example <- function(per_along){
  P1 <- matrix(nrow = 4, ncol = 4)
  P1[1, ] <- c(0, 1/2, 1/2, 0)
  P1[2, ] <- c(1/2, 0, 1/3, 1/6)
  v_diff <- c(1, 0, 0, 0) - c(1/4, 1/4, 1/4, 1/4)
  P1[3, ] <- c(1/4, 1/4, 1/4, 1/4) + v_diff * per_along
  v_diff <- c(1, 0, 0, 0) - c(0, 1, 0, 0)
  P1[4, ] <- c(0, 1, 0, 0) + v_diff * per_along
  return(P1)
}

last_vals <- c(0, 0.5, 1)
P1s <- map(last_vals, ~f_create_P1_example(.))

r_hat_vals_zfs <- matrix(nrow=nreplicates * length(Ls) * length(P1s), ncol=4)
r_hat_vals_s <- matrix(nrow=nreplicates * length(Ls) * length(P1s), ncol=4)
counter <- 1
for(k in 1:length(P1s)){
  for(j in seq_along(Ls)){
    print(paste0("k=", k, ", j=", j))
    for(i in 1:nreplicates){
      temp <- f_replicate(Ls[j], P0, P1s[[k]], 1)
      r_hat_vals_zfs[counter, ] <- c(k, Ls[j], i, temp$r_hat_zfs)
      r_hat_vals_s[counter, ] <- c(k, Ls[j], i, temp$r_hat_s)
      counter <- counter + 1
    }
  }
}
colnames(r_hat_vals_zfs) <- c("P1", "sample size", "iter", "value")
colnames(r_hat_vals_s) <- c("P1", "sample size", "iter", "value")
r_hat_vals_zfs <- as.data.frame(r_hat_vals_zfs) %>% 
  mutate(type="zfs-Rhat")
r_hat_vals_s <- as.data.frame(r_hat_vals_s) %>% 
  mutate(type="s-Rhat")

temp <- r_hat_vals_zfs %>% 
  bind_rows(r_hat_vals_s)
```

Plot
```{r}
r_star_vals <- temp %>% 
  mutate(P1=if_else(P1==1, "P1", if_else(P1==2, "P2", "P3"))) %>% 
  mutate(`sample size`=as.character(`sample size`)) %>% 
  mutate(`sample size`=if_else(`sample size`=="10000", "10,000", `sample size`)) %>% 
  mutate(`sample size`=as.factor(`sample size`)) %>% 
  mutate(`sample size`=fct_relevel(`sample size`, "1000", "2000", "5000", "10,000"))
a_sum <- r_star_vals %>%
  group_by(P1, `sample size`, type) %>%
  summarise(lower=quantile(value, 0.025),
         upper=quantile(value, 0.975),
         middle=quantile(value, 0.5))
r_star_vals %>% 
  left_join(a_sum) %>% 
  ggplot(aes(x=as.factor(`sample size`), y=value)) +
  geom_jitter(width = 0.2, colour="grey") +
  geom_pointrange(aes(ymin=lower, y=middle, ymax=upper)) +
  facet_grid(vars(P1), vars(type)) +
  geom_hline(yintercept = 1, linetype=2) +
  scale_y_continuous(limits=c(NA, NA)) +
  xlab("Sample size") +
  ylab(TeX("$R*$")) +
  theme(axis.text = element_text(colour="black", size=16),
        axis.title = element_text(colour="black", size=16),
        strip.text.y = element_text(colour="black", size=16),
        legend.position = "none",
        title = element_text(colour="black", size=16))
```

