---
title: "Hyperparameter sensitivity"
output: html_notebook
---

```{r}
rm(list=ls())
library(tidyverse)
library(reshape2)
library(rstan)
library(latex2exp)
library(caret)
library(gbm)
options(mc.cores=4)
rstan_options(auto_write = TRUE)
source("monitornew.R")
source("r_star_monitor.R")
```

# GBM
AR1 model
```{r}
f_ar1 <- function(rho, sigma, L){
  x <- vector(length = L)
  x[1] <- rnorm(1, 0, sd=sigma)
  for(i in 2:L)
    x[i] = rho * x[i - 1] + rnorm(1, 0, sd=sigma)
  return(x)
}

# Generates three chains with same var; one with a different var
f_generate_lower_var_four <- function(var_ratio, rho, sigma, L){
  x <- matrix(nrow = L, ncol = 4)
  for(i in 1:3)
    x[, i] <- f_ar1(rho, sigma, L)
  z <- f_ar1(rho, sigma * sqrt(var_ratio), L)
  x[, 4] <- z
  return(x)
}
```

```{r}
f_data_ar1 <- function(){
  temp <- f_generate_lower_var_four(1/3, 0.3, 1, 1000)
  a_array <- array(dim=c(1000, 4, 1))
  a_array[,,1] <- temp
  return(a_array)
}

f_replicate_hyper <- function(m_parameters, f_data_generator){
  
  a_array <- f_data_generator()
  
  laccuracy <- vector(length = nrow(m_parameters))
  for(i in 1:nrow(m_parameters))
    laccuracy[i] <- r_star(a_array,
                           caret_default=expand.grid(interaction.depth=m_parameters$int.depth[i],
                                                     n.trees = m_parameters$n.trees[i],
                                                     shrinkage=0.1,
                                                     n.minobsinnode=10))
  return(laccuracy)
}


f_replicate_r_star <- function(nreplicates, m_parameters, f_data_generator){
  r_star_vals <- matrix(nrow = nreplicates, ncol=nrow(m_parameters))
  for(i in 1:nreplicates){
      print(i)
    
    temp <- f_replicate_hyper(m_parameters, f_data_generator)
    r_star_vals[i, ] <- temp
  }
  r_star_vals <- r_star_vals %>% 
    t() %>% 
    as.data.frame()
  r_star_vals1 <- m_parameters %>% cbind(r_star_vals)
  return(r_star_vals1)
}

m_parameters <- expand_grid(int.depth=seq(1, 7, 2),
                            n.trees=c(1, 10, 50, 100))
r_star_vals <- f_replicate_r_star(2, m_parameters, f_data_ar1)

# saveRDS(r_star_vals, "../data/ar1_sensitivity.rds")
g1 <- readRDS("../data/hypers_ar1.rds")$r_star %>% 
  melt(id.vars=c("int.depth", "n.trees")) %>% 
  group_by(int.depth, n.trees) %>% 
  summarise(lower=quantile(value, 0.25),
            middle=quantile(value, 0.5),
            upper=quantile(value, 0.75)) %>% 
  mutate(default=if_else(int.depth==3&n.trees==50, 1, 0)) %>% 
  ggplot(aes(x=as.factor(n.trees), y=middle, colour=as.factor(int.depth), group=as.factor(int.depth))) +
  geom_pointrange(aes(ymin=lower, ymax=upper, shape=as.factor(default)),
                  position=position_dodge2(width=0.1)) +
  geom_line() +
  xlab("# trees") +
  ylab("R*") +
  theme(text = element_text(size=16, colour="black"),
        axis.text = element_text(colour="black"),
        legend.position = c(0.7, 0.25)) +
  scale_y_continuous(limits=c(0.95, 1.3)) +
  geom_hline(yintercept = 1, linetype=2) +
  scale_color_brewer("Int. depth", palette = "Dark2") +
  guides(colour = guide_legend(nrow = 2, byrow = T)) +
  scale_shape(guide="none") +
  ggtitle("A. GBM")
```


8 schools
```{r}
source("eight_schools.data.R")
eight_schools <- list(J=J, y=y, sigma=sigma)
model_cp <- stan_model("eight_schools_cp.stan")
model_ncp <- stan_model("eight_schools_ncp.stan")

f_data_8_schools <- function(){
  fit_ncp <- sampling(
    model_ncp, data = eight_schools,
    iter = 2000, chains = 4, refresh = 0,
    control = list(adapt_delta = 0.95)
    )
  x_ncp <- rstan::extract(fit_ncp, permuted=F)
}

m_parameters <- expand_grid(int.depth=c(1, 3, 5),
                            n.trees=c(1, 50, 200))
r_star_vals <- f_replicate_r_star(20, m_parameters, f_data_ar1)


g1a <- readRDS("../data/hypers_8_schools.rds")$r_star %>% 
  melt(id.vars=c("int.depth", "n.trees")) %>% 
  group_by(int.depth, n.trees) %>% 
  summarise(lower=quantile(value, 0.25),
            middle=quantile(value, 0.5),
            upper=quantile(value, 0.75)) %>% 
  mutate(default=if_else(int.depth==3&n.trees==50, 1, 0)) %>% 
  ggplot(aes(x=as.factor(n.trees), y=middle, colour=as.factor(int.depth), group=as.factor(int.depth))) +
  geom_pointrange(aes(ymin=lower, ymax=upper, shape=as.factor(default)),
                  position=position_dodge2(width=0.1)) +
  geom_line() +
  xlab("# trees") +
  ylab("R*") +
  theme(text = element_text(size=16, colour="black"),
        axis.text = element_text(colour="black"),
        legend.position = c(0.7, 0.7)) +
  scale_y_continuous(limits=c(0.95, 1.6)) +
  geom_hline(yintercept = 1, linetype=2) +
  scale_color_brewer("Int. depth", palette = "Dark2") +
  guides(colour = guide_legend(nrow = 2, byrow = T)) +
  scale_shape(guide="none") +
  ggtitle("A. GBM")
```

Cauchy
```{r}
f_data_cauchy <- function(){
  fit_nom <- stan(file = 'cauchy_alt_1.stan',
                refresh = 0)
  x <- rstan::extract(fit_nom, permuted=F)
  return(x)
}

# m_parameters <- expand_grid(int.depth=c(3, 7, 11),
#                             n.trees=c(50, 100, 400))
# r_star_vals <- f_replicate_r_star(2, m_parameters, f_data_cauchy)

g1b <- readRDS("../data/hypers_cauchy.rds")$r_star %>% 
  melt(id.vars=c("int.depth", "n.trees")) %>% 
  group_by(int.depth, n.trees) %>% 
  summarise(lower=quantile(value, 0.25),
            middle=quantile(value, 0.5),
            upper=quantile(value, 0.75)) %>% 
  mutate(default=if_else(int.depth==3&n.trees==50, 1, 0)) %>% 
  ggplot(aes(x=as.factor(n.trees), y=middle, colour=as.factor(int.depth), group=as.factor(int.depth))) +
  geom_pointrange(aes(ymin=lower, ymax=upper, shape=as.factor(default)),
                  position=position_dodge2(width=0.1)) +
  geom_line() +
  xlab("# trees") +
  ylab("R*") +
  theme(text = element_text(size=16, colour="black"),
        axis.text = element_text(colour="black"),
        legend.position = c(0.7, 0.25)) +
  scale_y_continuous(limits=c(0.95, 2.8)) +
  geom_hline(yintercept = 1, linetype=2) +
  scale_color_brewer("Int. depth", palette = "Dark2") +
  guides(colour = guide_legend(nrow = 2, byrow = T)) +
  scale_shape(guide="none") +
  ggtitle("A. GBM")
```

Normal
```{r}
readRDS("../data/hypers_normal_250.rds")$r_star %>% 
  melt(id.vars=c("int.depth", "n.trees")) %>% 
  group_by(int.depth, n.trees) %>% 
  summarise(lower=quantile(value, 0.25),
            middle=quantile(value, 0.5),
            upper=quantile(value, 0.75)) %>% 
  mutate(default=if_else(int.depth==3&n.trees==50, 1, 0)) %>% 
  ggplot(aes(x=as.factor(n.trees), y=middle, colour=as.factor(int.depth), group=as.factor(int.depth))) +
  geom_pointrange(aes(ymin=lower, ymax=upper, shape=as.factor(default)),
                  position=position_dodge2(width=0.1)) +
  geom_line() +
  xlab("# trees") +
  ylab("R*") +
  theme(text = element_text(size=16, colour="black"),
        axis.text = element_text(colour="black"),
        legend.position = c(0.7, 0.25)) +
  scale_y_continuous(limits=c(0.95, 2.8)) +
  geom_hline(yintercept = 1, linetype=2) +
  scale_color_brewer("Int. depth", palette = "Dark2") +
  guides(colour = guide_legend(nrow = 2, byrow = T)) +
  scale_shape(guide="none") +
  ggtitle("A. GBM")
```


# RF hyperparameters
AR1
```{r}
g2 <- readRDS("../data/hypers_rf_ar1.rds")$r_star %>%
  melt(id.vars="mtry") %>%
  group_by(mtry) %>%
  summarise(lower=quantile(value, 0.25),
            middle=quantile(value, 0.5),
            upper=quantile(value, 0.75)) %>%
  mutate(default=if_else(mtry==1, 1, 0)) %>% 
  ggplot(aes(x=mtry, y=middle)) +
  geom_pointrange(aes(ymin=lower, ymax=upper, shape=as.factor(default)),
                  position=position_dodge2(width=0.1)) +
  geom_line() +
  xlab(TeX("$m_{try}$")) +
  ylab("R*") +
  theme(text = element_text(size=16, colour="black"),
        axis.text = element_text(colour="black"),
        legend.position = c(0.7, 0.25)) +
  scale_y_continuous(limits=c(0.95, 1.3)) +
  scale_x_continuous(breaks=c(1, 2), limits = c(0.5, 2.5)) +
  geom_hline(yintercept = 1, linetype=2) +
  scale_color_brewer("Int. depth", palette = "Dark2") +
  guides(colour = guide_legend(nrow = 2, byrow = T)) +
  scale_shape(guide="none") +
  ggtitle("B. RF")
pdf("../output/hypers_ar1.pdf", width = 12, height = 6)
multiplot(g1, g2, cols=2)
dev.off()
```

8 schools
```{r}
g2a <- readRDS("../data/hypers_rf_8_schools.rds")$r_star %>%
  melt(id.vars="mtry") %>%
  group_by(mtry) %>%
  summarise(lower=quantile(value, 0.25),
            middle=quantile(value, 0.5),
            upper=quantile(value, 0.75)) %>%
  mutate(default=if_else(mtry==4, 1, 0)) %>% 
  ggplot(aes(x=as.factor(mtry), y=middle)) +
  geom_pointrange(aes(ymin=lower, ymax=upper, shape=as.factor(default)),
                  position=position_dodge2(width=0.1)) +
  geom_line(aes(group=1)) +
  xlab("# features") +
  ylab("R*") +
  theme(text = element_text(size=16, colour="black"),
        axis.text = element_text(colour="black"),
        legend.position = c(0.7, 0.25)) +
  scale_y_continuous(limits=c(0.95, 1.6)) +
  geom_hline(yintercept = 1, linetype=2) +
  scale_color_brewer("Int. depth", palette = "Dark2") +
  guides(colour = guide_legend(nrow = 2, byrow = T)) +
  scale_shape(guide="none") +
  ggtitle("B. RF")

pdf("../output/hypers_8_schools.pdf", width = 12, height = 6)
multiplot(g1a, g2a, cols=2)
dev.off()
```
Cauchy
```{r}
g2b <- readRDS("../data/hypers_rf_cauchy.rds")$r_star %>%
  melt(id.vars="mtry") %>%
  group_by(mtry) %>%
  summarise(lower=quantile(value, 0.25),
            middle=quantile(value, 0.5),
            upper=quantile(value, 0.75)) %>%
  mutate(default=if_else(mtry==12, 1, 0)) %>% 
  ggplot(aes(x=as.factor(mtry), y=middle)) +
  geom_pointrange(aes(ymin=lower, ymax=upper, shape=as.factor(default)),
                  position=position_dodge2(width=0.1)) +
  geom_line(aes(group=1)) +
  xlab("# features") +
  ylab("R*") +
  theme(text = element_text(size=16, colour="black"),
        axis.text = element_text(colour="black"),
        legend.position = c(0.7, 0.25)) +
  scale_y_continuous(limits=c(0.95, 2.8)) +
  geom_hline(yintercept = 1, linetype=2) +
  scale_color_brewer("Int. depth", palette = "Dark2") +
  guides(colour = guide_legend(nrow = 2, byrow = T)) +
  scale_shape(guide="none") +
  ggtitle("B. RF")
pdf("../output/hypers_cauchy.pdf", width = 12, height = 6)
multiplot(g1b, g2b, cols=2)
dev.off()
```

Normal
```{r}
readRDS("../data/hypers_rf_normal_250.rds")$r_star %>%
  melt(id.vars="mtry") %>%
  group_by(mtry) %>%
  summarise(lower=quantile(value, 0.25),
            middle=quantile(value, 0.5),
            upper=quantile(value, 0.75)) %>%
  ggplot(aes(x=as.factor(mtry), y=middle, group=1)) +
  geom_pointrange(aes(ymin=lower, ymax=upper), position=position_dodge2(width=0.1)) +
  geom_line() +
  xlab("# features") +
  ylab("R*") +
  theme(text = element_text(size=16, colour="black"),
        axis.text = element_text(colour="black"),
        legend.position = c(0.7, 0.25)) +
  scale_y_continuous(limits=c(0.95, NA)) +
  geom_hline(yintercept = 1, linetype=2) +
  scale_color_brewer("Int. depth", palette = "Dark2") +
  guides(colour = guide_legend(nrow = 2, byrow = T))
```


