---
title: "Ovarian and prostate models"
output: html_notebook
---

```{r}
rm(list=ls())
library(tidyverse)
library(reshape2)
library(rstan)
library(latex2exp)
library(caret)
library(gbm)
library(mvtnorm)
options(mc.cores=4)
rstan_options(auto_write = TRUE)
source("monitornew.R")
source("r_star_monitor.R")
```

# Ovarian data
```{r}
ovarian <- read.csv("../data/ovarian.csv", header=FALSE)

y<-ovarian[,1537]
x<-ovarian[,1:1536]

n = nrow(x);
p = ncol(x);

## regularized horseshoe prior
p0 <- 5
sigma <- 1
tau0 <- p0/(p-p0)*sigma/sqrt(n)
## data
data <- list(n = n, d = ncol(x), x = x, y = y,
             nu_local = 1, nu_global = 1, scale_global = tau0,
             scale_icept=5, slab_scale=2, slab_df=100)

model <- stan_model("bernoulli_logit_glm_rhs.stan")
```

With 4 long chains
```{r}
fit <- sampling(model, data=data, chains=4, iter=9000, warmup=1000,
                control=list(adapt_delta = 0.8, max_treedepth=10), cores=4, thin=10)
saveRDS(fit, "../data/ovarian_long.rds")
fit <- readRDS("../data/ovarian_long.rds")

x <- rstan::extract(fit, permuted=F)

mon <- monitor_extra(x)
saveRDS(mon, "../data/ovarian_long_mon.rds")
full_data <- rstan::extract(fit, permuted=F)
r_star <- r_star(full_data, method = "gbm", uncertainty = T)
saveRDS(r_star, "../data/ovarian_long_r_star.rds")
```

With 16, shorter, chains
```{r}
fit <- sampling(model, data=data, chains=16, iter=1000, warmup=500,
                control=list(adapt_delta = 0.8, max_treedepth=10), cores=4)
saveRDS(fit, "../data/ovarian_short.rds")
fit <- readRDS("../data/ovarian_short.rds")

x <- rstan::extract(fit, permuted=F)
mon <- monitor_extra(x)
saveRDS(mon, "../data/ovarian_short_mon.rds")
full_data <- rstan::extract(fit, permuted=F)
r_star <- r_star(full_data, method = "gbm", uncertainty = T)
saveRDS(r_star, "../data/ovarian_short_r_star.rds")
```

Plot R* and Rhat
```{r}
r_star_longer <- readRDS("../data/ovarian_long_r_star.rds")
r_star_shorter <- readRDS("../data/ovarian_short_r_star.rds")

mon_longer <- readRDS("../data/ovarian_long_mon.rds")
mon_shorter <- readRDS("../data/ovarian_short_mon.rds")

# find max of rank normalized split-Rhat and rank normalized folded-split-Rhat
f_rhat_max <- function(mon) {
  rhat <- mon$zsRhat
  rhat1 <- mon$zfsRhat
  rhat <- tibble(rhat, rhat1) %>% 
    apply(1, max)
  return(rhat)
}


g <- tibble(long=r_star_longer, short=r_star_shorter, metric="A. R*") %>% 
  bind_rows(tibble(long=f_rhat_max(mon_longer), short=f_rhat_max(mon_shorter), metric="B. Split-Rhat"))%>% 
  bind_rows(tibble(long=mon_longer$zsseff, short=mon_shorter$zsseff, metric="C. Bulk-ESS")) %>% 
  bind_rows(tibble(long=mon_longer$tailseff, short=mon_shorter$tailseff, metric="D. Tail-ESS")) %>% 
  melt(id.vars="metric") %>% 
  mutate(metric=fct_relevel(as.factor(metric), "A. R*", "B. Split-Rhat", "C. Bulk-ESS", "D. Tail-ESS")) %>% 
  ggplot(aes(x=value, fill=as.factor(variable))) +
  geom_histogram(position="identity", alpha=0.6) +
  facet_wrap(~metric, scales="free") +
  scale_fill_grey("MCMC detail", labels=c("4 chains: long", "16 chains: short")) +
  theme(strip.text.x = element_text(size = 20, colour="black"),
        text = element_text(size=18, colour="black"),
        axis.text = element_text(size=18, colour="black"),
        legend.text = element_text(size=18, colour="black"),
        axis.title = element_text(size=18, colour="black"),
        axis.title.x = element_blank(),
        legend.position = "top") +
  ylab("Count")
ggsave("../output/ovarian.pdf", g, width = 12, height = 8)
```

# Prostate
```{r}
prostate <- read.csv("../data/prostate.csv", header=FALSE)

y<-prostate[,5967]
x<-prostate[,1:5966]

n = nrow(x);
p = ncol(x);

## regularized horseshoe prior
p0 <- 5
sigma <- 1
tau0 <- p0/(p-p0)*sigma/sqrt(n)
## data
data <- list(n = n, d = ncol(x), x = x, y = y,
             nu_local = 1, nu_global = 1, scale_global = tau0,
             scale_icept=5, slab_scale=2, slab_df=100)

model <- stan_model("bernoulli_logit_glm_rhs.stan")
```

With 4 long chains
```{r}
fit <- sampling(model, data=data, chains=4, iter=9000, warmup=1000,
                control=list(adapt_delta = 0.8, max_treedepth=10), cores=4, thin=10)
saveRDS(fit, "../data/prostate_long.rds")
fit <- readRDS("../data/prostate_long.rds")

x <- rstan::extract(fit, permuted=F)

mon <- monitor_extra(x)
saveRDS(mon, "../data/prostate_long_mon.rds")
full_data <- rstan::extract(fit, permuted=F)

# Thin data again
r_star <- r_star(full_data[, , seq(1, 18106, 5)], method = "gbm", uncertainty = T)
saveRDS(r_star, "../data/prostate_long_r_star.rds")
```


With 16, shorter, chains
```{r}
fit <- sampling(model, data=data, chains=16, iter=1000, warmup=500,
                control=list(adapt_delta = 0.8, max_treedepth=10), cores=4)
saveRDS(fit, "../data/prostate_short.rds")
fit <- readRDS("../data/prostate_short.rds")

x <- rstan::extract(fit, permuted=F)
mon <- monitor_extra(x)
saveRDS(mon, "../data/prostate_short_mon.rds")
full_data <- rstan::extract(fit, permuted=F)
r_star <- r_star(full_data[, , seq(1, 18106, 5)], method = "gbm", uncertainty = T)
saveRDS(r_star, "../data/prostate_short_r_star.rds")
```

Plot R* and Rhat
```{r}
r_star_longer <- readRDS("../data/prostate_long_r_star.rds")
r_star_shorter <- readRDS("../data/prostate_short_r_star.rds")

mon_longer <- readRDS("../data/prostate_long_mon.rds")
mon_shorter <- readRDS("../data/prostate_short_mon.rds")

my_breaks <- function(x) { if (max(x) < 10) c(0.95, max(x)) else c(0, max(x)) }

g <- tibble(long=r_star_longer, short=r_star_shorter, metric="A. R*") %>% 
  bind_rows(tibble(long=f_rhat_max(mon_longer), short=f_rhat_max(mon_shorter), metric="B. Split-Rhat")) %>% 
  bind_rows(tibble(long=mon_longer$zsseff, short=mon_shorter$zsseff, metric="C. Bulk-ESS")) %>% 
  bind_rows(tibble(long=mon_longer$tailseff, short=mon_shorter$tailseff, metric="D. Tail-ESS")) %>% 
  melt(id.vars="metric") %>% 
  mutate(metric=fct_relevel(as.factor(metric), "A. R*", "B. Split-Rhat", "C. Bulk-ESS", "D. Tail-ESS")) %>% 
  ggplot(aes(x=value, fill=as.factor(variable))) +
  geom_histogram(position="identity", alpha=0.6) +
  facet_wrap(~metric, scales="free") +
  scale_fill_grey("MCMC detail", labels=c("4 chains: long", "16 chains: short")) +
  theme(strip.text.x = element_text(size = 20, colour="black"),
        text = element_text(size=18, colour="black"),
        axis.text = element_text(size=18, colour="black"),
        legend.text = element_text(size=18, colour="black"),
        axis.title = element_text(size=18, colour="black"),
        axis.title.x = element_blank(),
        legend.position = "top") +
  ylab("Count") +
  scale_x_continuous(limits=my_breaks)
ggsave("../output/prostate.pdf", g, width = 12, height = 8)
```