---
title: "Examining the effect of sampler trends on R*"
output: html_notebook
---

```{r}
rm(list=ls())
library(tidyverse)
library(reshape2)
library(rstan)
library(latex2exp)
library(caret)
library(gbm)
library(mvtnorm)
options(mc.cores=4)
rstan_options(auto_write = TRUE)
source("monitornew.R")

f_fit_rf_predict <- function(r){
  rand_samples <- sample(1:nrow(r), 0.7 * nrow(r))
  nvars <- ncol(r) - 1
  training_data <- r[rand_samples, ]
  testing_data <- r[-rand_samples, ]

  gbmFit1 <- train(chain ~ ., data = training_data, 
                 method = "rf",
                 trControl = trainControl(method = 'none'), 
                    tuneGrid = tibble(mtry=nvars), verbose=FALSE)
  plda <- predict(object=gbmFit1, newdata=testing_data)
  a_accuracy <- 
    tibble(predicted=plda, actual=testing_data$chain) %>%
    mutate(correct=if_else(predicted==actual, 1, 0)) %>% 
    summarise(mean(correct)) %>% 
    pull()
  return(a_accuracy)
}

f_fit_gbm_predict <- function(r){
  rand_samples <- sample(1:nrow(r), 0.7 * nrow(r))
  nvars <- ncol(r) - 1
  training_data <- r[rand_samples, ]
  testing_data <- r[-rand_samples, ]
  
  grids <- tibble(interaction.depth=c(3), 
                             n.trees = 50,
                             shrinkage=c(0.1),
                             n.minobsinnode=10)

  gbmFit1 <- train(chain ~ ., data = training_data, 
                 method = "gbm",
                 trControl = trainControl(method = 'none'), 
                    tuneGrid = grids, verbose=FALSE)
  plda <- predict(object=gbmFit1, newdata=testing_data)
  a_accuracy <- 
    tibble(predicted=plda, actual=testing_data$chain) %>%
    mutate(correct=if_else(predicted==actual, 1, 0)) %>% 
    summarise(mean(correct)) %>% 
    pull()
  return(a_accuracy)
}

f_fit_both <- function(r){
  r1 <- f_fit_rf_predict(r)
  r2 <- f_fit_gbm_predict(r)
  return(list(rf=r1, gbm=r2))
}
models <- c("gbm", "rf")
```

# Consistent trend across all chains
Repeating analysis from Vehtari et a. appendix B
```{r}
conds <- expand.grid(
  iters = c(250, 1000, 4000), 
  trend = c(0, 0.25, 0.5, 0.75, 1),
  rep = 1:10
)
res <- vector("list", 2 * nrow(conds))
chains = 4
kkk <- 1
for(mm in 1:2){
  for (i in 1:nrow(conds)) {
    print(i)
    iters <- conds[i, "iters"]
    trend <- conds[i, "trend"]
    rep <- conds[i, "rep"]
    r <- array(rnorm(iters * chains), c(iters, chains))
    r <- r + seq(-trend, trend, length.out = iters)
    rs <- as.data.frame(monitor_extra(r))
    
    # R* calculation
    r1 <- r %>% 
      as.data.frame() %>% 
      melt(id.vars = NULL) %>% 
      mutate(chain=as.factor(variable)) %>% 
      select(-variable) %>% 
    mutate(ones=rnorm(length(chain)))
    if(mm==1)
      a_accuracy <- f_fit_gbm_predict(r1)
    else
      a_accuracy <- f_fit_rf_predict(r1)
    
    # Split R* calculation
    half_rows <- nrow(r) / 2
    r2 <- cbind(r[1:half_rows, ], r[(half_rows+1):nrow(r), ]) %>% 
      as.data.frame() %>% 
      melt(id.vars = NULL) %>% 
      mutate(chain=as.factor(variable)) %>% 
      select(-variable) %>% 
    mutate(ones=rnorm(length(chain)))
    if(mm==1)
      b_accuracy <- f_fit_gbm_predict(r2)
    else
      b_accuracy <- f_fit_rf_predict(r2)
    
    
    res[[kkk]] <- cbind(iters, trend, rep, rs, "Rstar"=a_accuracy * n_distinct(r1$chain),
                      "Rstar_split"=b_accuracy * n_distinct(r2$chain),
                      method=models[mm])
    kkk <- kkk + 1
  }
}
res <- bind_rows(res)
saveRDS(res, "../output/experiment_trends_all_dim.rds")
```

Plot
```{r}
res <- readRDS("../output/experiment_trends_all_dim.rds")
g <-
  res %>%
  select(iters, trend, Rstar, Rstar_split, method) %>%
  melt(id.vars=c("iters", "trend", "method")) %>%
  mutate(variable=case_when(variable=="Rstar"~"A. R*",
                            variable=="Rstar_split"~"B. Split-R*")) %>%
  mutate(method=as.character(method)) %>% 
  mutate(method=if_else(method=="gbm", "GBM", "RF")) %>% 
  ggplot(aes(y = value, x = trend)) +
  geom_jitter(aes(colour=as.factor(method), shape=as.factor(method))) +
  facet_grid(vars(iters), vars(variable)) +
  geom_hline(yintercept = 1) +
  theme(strip.text.x = element_text(size=16, colour="black"),
        strip.text.y = element_text(size=16, colour="black"),
        axis.text.x = element_text(size=16, colour="black"),
        axis.text.y = element_text(size=16, colour="black"),
        axis.title = element_text(size=16, colour="black"),
        legend.text = element_text(size=16, colour="black"),
        legend.title = element_text(size=16, colour="black")) +
  xlab("Trend") +
  ylab("Value") +
  scale_colour_grey("Classifier") +
  scale_shape("Classifier")
ggsave("../output/trends_all_dim.pdf", g, width = 8, height = 6)
```


# Trend in a single dimension
```{r}
conds <- expand.grid(
  iters = c(250, 1000, 4000), 
  trend = c(0, 0.25, 0.5, 0.75, 1),
  rep = 1:10,
  dimension = c(1, 5, 10, 20)
)
res <- vector("list", nrow(conds))
chains = 4
kkk <- 1
for(mm in 1:2){
  for (i in 1:nrow(conds)) {
    print(i)
    iters <- conds[i, "iters"]
    trend <- conds[i, "trend"]
    rep <- conds[i, "rep"]
    dimension <- conds[i, "dimension"]
    r <- array(rnorm(iters * chains * dimension), c(iters, chains, dimension))
    r[, , 1] <- r[, , 1] + seq(-trend, trend, length.out = iters)
    rs <- as.data.frame(monitor_extra(r))
    r_2d <- matrix(nrow = iters * chains, ncol=(dimension + 2))
    k <- 1
    for(ii in 1:iters){
      for(j in 1:chains){
        r_2d[k, ] <- c(ii, j, r[ii, j, ])
        k <- k + 1
      }
    }
    r_2d <- r_2d %>%
      as.data.frame()
    colnames(r_2d)[1:2] <- c("iter", "chain")
    
    # R* calculation
    r1 <- r_2d %>% 
      arrange(chain, iter) %>% 
      select(-iter) %>% 
      mutate(chain=as.factor(chain))
    if(dimension==1)
      r1 <- r1 %>% mutate(ones=rnorm(length(chain)))
    if(mm==1)
      a_accuracy <- f_fit_gbm_predict(r1)
    else
      a_accuracy <- f_fit_rf_predict(r1)
    
    # Split R* calculation
    half_rows <- iters / 2
    r_1h <- r_2d %>% 
      filter(iter<=half_rows)
    r_2h <- r_2d %>% 
      filter(iter>half_rows) %>% 
      mutate(chain=chain + chains)
    r2 <- bind_rows(r_1h, r_2h) %>% 
      select(-iter) %>% 
      mutate(chain=as.factor(chain))
    if(dimension==1)
      r2 <- r2 %>% mutate(ones=rnorm(length(chain)))
    if(mm==1)
      b_accuracy <- f_fit_gbm_predict(r2)
    else
      b_accuracy <- f_fit_rf_predict(r2)
    
    res[[kkk]] <- cbind(iters, trend, rep, dimension, rs,
                        "Rstar"=a_accuracy * n_distinct(r1$chain),
                        "Rstar_split"=b_accuracy * n_distinct(r2$chain),
                        method=models[mm])
    kkk <- kkk + 1
  }
}
res <- bind_rows(res)
saveRDS(res, "../output/experiment_trends_one_dim.rds")
```

Plot
```{r}
g <- readRDS("../output/experiment_trends_one_dim.rds") %>%
  select(trend, iters, rep, dimension, Rstar_split, method) %>%
  unique() %>%
  select(-rep) %>%
  melt(c("trend", "iters", "dimension", "method")) %>%
  filter(variable=="Rstar_split") %>%
  mutate(method=as.character(method)) %>% 
  mutate(method=if_else(method=="gbm", "GBM", "RF")) %>% 
  ggplot(aes(y = value, x = trend)) +
  geom_jitter(aes(colour=as.factor(method),
                  shape=as.factor(method))) +
  facet_grid(vars(iters), vars(dimension)) +
  geom_hline(yintercept = 1) +
  theme(strip.text.x = element_text(size=16, colour="black"),
        strip.text.y = element_text(size=16, colour="black"),
        axis.text.x = element_text(size=16, colour="black"),
        axis.text.y = element_text(size=16, colour="black"),
        axis.title = element_text(size=16, colour="black"),
        legend.text = element_text(size=16, colour="black"),
        legend.title = element_text(size=16, colour="black")) +
  xlab("Trend") +
  ylab("Value") +
  scale_colour_grey("Classifier") +
  scale_shape("Classifier")
g

ggsave("../output/trends_one_dim.pdf", g, width = 8, height = 6)
```

# Trend in the joint distribution over time
```{r}
library(mvtnorm)
rmvrnorm2D <- function(n, mux, muy, sigmax, sigmay, rho){
  return(rmvnorm(n, c(mux, muy),
                 matrix(c(sigmax^2, sigmax * sigmay * rho,
                          sigmax * sigmay * rho, sigmay^2),
                        ncol = 2)))
}

conds <- expand.grid(
  iters = c(250, 1000, 4000), 
  rep = 1:10,
  rho = c(0, 0.2, 0.4, 0.6, 0.8)
)
res <- vector("list", nrow(conds))
chains = 4
kkk <- 1
for(mm in 1:2){
  for (i in 1:nrow(conds)) {
    print(i)
    iters <- conds[i, "iters"]
    rep <- conds[i, "rep"]
    rho <- conds[i, "rho"]
    rho_trend <- seq(-rho, rho, length.out = iters)
    r <- array(dim=c(iters, chains, 2))
    for(j in 1:chains)
      for(jj in 1:iters)
        r[jj, j, ] <- rmvrnorm2D(1, 0, 0, 1, 1, rho_trend[jj])
    # take max as just using the Rhat values
    rs <- as.data.frame(monitor_extra(r)) %>% 
      apply(2, max)
    
   r_2d <- matrix(nrow = iters * chains, ncol=(2 + 2))
    k <- 1
    for(ii in 1:iters){
      for(j in 1:chains){
        r_2d[k, ] <- c(ii, j, r[ii, j, ])
        k <- k + 1
      }
    }
    r_2d <- r_2d %>%
      as.data.frame()
    colnames(r_2d)[1:2] <- c("iter", "chain")
    
    # R* calculation
    r1 <- r_2d %>% 
      arrange(chain, iter) %>% 
      select(-iter) %>% 
      mutate(chain=as.factor(chain))
    if(mm==1)
        a_accuracy <- f_fit_gbm_predict(r1)
      else
        a_accuracy <- f_fit_rf_predict(r1)
    
    # Split R* calculation
    half_rows <- iters / 2
    r_1h <- r_2d %>% 
      filter(iter<=half_rows)
    r_2h <- r_2d %>% 
      filter(iter>half_rows) %>% 
      mutate(chain=chain + chains)
    r2 <- bind_rows(r_1h, r_2h) %>% 
      select(-iter) %>% 
      mutate(chain=as.factor(chain))
    if(mm==1)
        b_accuracy <- f_fit_gbm_predict(r2)
      else
        b_accuracy <- f_fit_rf_predict(r2)
    
    res[[kkk]] <- cbind(iters, rep, rho, t(rs), "Rstar"=a_accuracy * n_distinct(r1$chain),
                      "Rstar_split"=b_accuracy * n_distinct(r2$chain),
                      method=models[mm])
    kkk <- kkk + 1
  }
}
res1 <- do.call(rbind, res)
saveRDS(res1, "../output/experiment_trends_joint_distribution.rds")
```

Plot
```{r}
# remove double iterates for rhat from rfs
g <- readRDS("../output/experiment_trends_joint_distribution.rds") %>%
  as.data.frame() %>%
  dplyr::select(iters, rho, rep, zsRhat, zfsRhat, Rstar_split, method) %>%
  unique() %>%
  dplyr::select(-rep) %>%
  mutate(zsRhat=max(as.numeric(as.character(zsRhat), as.numeric(as.character(zfsRhat))))) %>% 
  dplyr::select(-zfsRhat) %>% 
  melt(c("rho", "iters", "method")) %>%
  filter(!((method=="rf")&(variable=="zsRhat"))) %>% 
  mutate(value=as.numeric(as.character(value))) %>% 
  mutate(variable=case_when(variable=="zsRhat"~"A. Split-Rhat",
                            variable=="Rstar_split"~"B. Split-R*")) %>% 
  mutate(iters=as.numeric(as.character(iters))) %>% 
  mutate(method=as.character(method)) %>% 
  mutate(method=if_else(method=="rf", "RF", "GBM")) %>% 
  ggplot(aes(y = value, x = rho)) +
  geom_jitter(aes(colour=as.factor(method),
                  shape=as.factor(method))) +
  facet_grid(vars(iters), vars(variable)) +
  geom_hline(yintercept = 1) +
  theme(strip.text.x = element_text(size=16, colour="black"),
        strip.text.y = element_text(size=16, colour="black"),
        axis.text.x = element_text(size=16, colour="black"),
        axis.text.y = element_text(size=16, colour="black"),
        axis.title = element_text(size=16, colour="black"),
        legend.text = element_text(size=16, colour="black"),
        legend.title = element_text(size=16, colour="black")) +
  ylab("Value") +
  xlab(TeX("$\\rho$"))  +
  scale_colour_grey("Classifier") +
  scale_shape("Classifier")
g

ggsave("../output/trends_joint_distribution.pdf", g, width = 8, height = 6)
```


# Stationary -> non-stationary data
Vary rho of AR1 process from stationary->non-stationary generating process
```{r}
f_ar1 <- function(rho, sigma, L){
  x <- vector(length = L)
  x[1] <- rnorm(1, 0, sd=sigma)
  for(i in 2:L)
    x[i] = rho * x[i - 1] + rnorm(1, 0, sd=sigma)
  return(x)
}

conds <- expand.grid(
  iters = c(250, 1000, 4000), 
  trend = c(0, 0.25, 0.5, 0.75, 1),
  rep = 1:10,
  rho = c(0.8, 0.85, 0.9, 0.95, 0.975, 1)
)
res <- vector("list", nrow(conds))
chains = 4
sigma <- 1
kkk <- 1
for(mm in 1:2){
  for (i in 1:nrow(conds)) {
    print(i)
    iters <- conds[i, "iters"]
    trend <- conds[i, "trend"]
    rep <- conds[i, "rep"]
    rho <- conds[i, "rho"]
    r <- array(rnorm(iters * chains), c(iters, chains))
    for(j in 1:chains)
      r[, j] <- f_ar1(rho, sigma, iters)
    rs <- as.data.frame(monitor_extra(r))
    
    # R* calculation
    r1 <- r %>% 
      as.data.frame() %>% 
      melt(id.vars = NULL) %>% 
      mutate(chain=as.factor(variable)) %>% 
      select(-variable)
    if(ncol(r1)==2)
      r1 <- r1 %>% mutate(ones=rnorm(length(chain)))
    if(mm==1)
        a_accuracy <- f_fit_gbm_predict(r1)
      else
        a_accuracy <- f_fit_rf_predict(r1)
    
    # Split R* calculation
    half_rows <- nrow(r) / 2
    r2 <- cbind(r[1:half_rows, ], r[(half_rows+1):nrow(r), ]) %>% 
      as.data.frame() %>% 
      melt(id.vars = NULL) %>% 
      mutate(chain=as.factor(variable)) %>% 
      select(-variable)
    if(ncol(r2)==2)
      r2 <- r2 %>% mutate(ones=rnorm(length(chain)))
    if(mm==1)
        b_accuracy <- f_fit_gbm_predict(r2)
      else
        b_accuracy <- f_fit_rf_predict(r2)
    
    res[[kkk]] <- cbind(iters, trend, rep, rho, rs, "Rstar"=a_accuracy * n_distinct(r1$chain),
                      "Rstar_split"=b_accuracy * n_distinct(r2$chain),
                      method=models[mm])
    kkk <- kkk + 1
  }
}
res <- bind_rows(res)
saveRDS(res, "../output/experiment_trends_rho_nearer1.rds")

```

Plot
```{r}
res <- readRDS("../output/experiment_trends_rho_nearer1.rds") %>%
  mutate(method=as.character(method)) %>% 
  mutate(method=if_else(method=="gbm", "GBM", "RF"))

g <- ggplot(data = res, aes(x = rho, y = Rstar_split)) +
  geom_jitter(aes(colour=as.factor(method),
                  shape=as.factor(method))) +
  facet_grid(vars(iters)) +
  geom_hline(yintercept = 1) +
  ylab(TeX("Split-R*")) +
  xlab(TeX("$\\rho$")) +
  ylim(0, 6) +
  theme(strip.text.x = element_text(size=16, colour="black"),
        strip.text.y = element_text(size=16, colour="black"),
        axis.text.x = element_text(size=16, colour="black"),
        axis.text.y = element_text(size=16, colour="black"),
        axis.title = element_text(size=16, colour="black"),
        legend.text = element_text(size=16, colour="black"),
        legend.title = element_text(size=16, colour="black"))  +
  scale_colour_grey("Classifier") +
  scale_shape("Classifier")
ggsave("../output/trends_ar1.pdf", g, width = 8, height = 6)


res <- readRDS("../output/experiment_trends_rho_nearer1.rds") %>%
  mutate(method=as.character(method)) %>% 
  mutate(method=if_else(method=="gbm", "A. GBM", "B. RF"))

b_sum <- res %>%
  group_by(iters, rho, method) %>%
  summarise(lower=quantile(Rstar_split, 0.025),
            upper=quantile(Rstar_split, 0.975),
            Rstar_split=median(Rstar_split)) %>%
  mutate(type="summary")
res1 <- res %>%
  bind_rows(b_sum)

g <- ggplot(data = filter(res1, is.na(type)), aes(x = as.factor(iters), y = Rstar_split, group=rho)) +
  geom_jitter(width = 0.2, height = 0, colour="grey") +
  geom_pointrange(data=filter(res1, !is.na(type)), aes(ymin=lower, ymax=upper)) +
  geom_line(data=filter(res1, !is.na(type))) +
  facet_grid(vars(rho), vars(method), scales="free") +
  geom_hline(yintercept = 1) +
  ylab(TeX("Split-R*")) +
  xlab("# iterations") +
  theme(strip.text.x = element_text(size=16, colour="black"),
        strip.text.y = element_text(size=16, colour="black"),
        axis.text.x = element_text(size=16, colour="black"),
        axis.text.y = element_text(size=16, colour="black"),
        axis.title = element_text(size=16, colour="black"),
        legend.text = element_text(size=16, colour="black"),
        legend.title = element_text(size=16, colour="black"))

ggsave("../output/trends_ar1_transposed.pdf", g, width = 8, height = 6)
```

